import Link from "next/link";
import { Nav } from "@/components/nav";
import { requireRole } from "@/lib/auth";
export default async function Home() {
 const {role,supabase}=await requireRole(["ADMIN","SCANNER"]);
 if(role!=="ADMIN") return <><Nav/><main className="shell"><section className="welcome"><span className="eyebrow">CONTROL DE ACCESO</span><h1>Scanner listo</h1><p>Escanea la credencial de cada participante para validar su ingreso.</p><Link className="button primary" href="/scanner">Abrir scanner de cámara →</Link></section></main></>;
 const {data,error}=await supabase.from("participants").select("status"); const rows=(data ?? []) as {status:string}[];
 const stats=error?null:{registered:rows.length,checked:rows.filter((x: {status:string})=>x.status==="checked_in").length,pending:rows.filter((x: {status:string})=>x.status==="pending").length,cancelled:rows.filter((x: {status:string})=>x.status==="cancelled").length};
 return <><Nav/><main className="shell"><div className="pagehead"><div><span className="eyebrow">PANEL DE CONTROL</span><h1>Dashboard</h1><p>Resumen actualizado desde la base de datos.</p></div><div className="actions"><Link className="button primary" href="/people/new">＋ Registrar persona</Link><Link className="button secondary" href="/scanner">▣ Escanear QR</Link></div></div>
 {error?<div className="notice error">No fue posible cargar los datos. Ejecuta la migración de Supabase y configura las variables de conexión.</div>:<><section className="metrics">{[["Registrados",stats!.registered],["Ingresados",stats!.checked],["Pendientes",stats!.pending],["Anulados",stats!.cancelled]].map(([label,n])=><article className="metric" key={label}><span>{label}</span><strong>{n}</strong><small>Personas</small></article>)}</section><section className="attendance"><div><span className="eyebrow">ASISTENCIA</span><h2>{stats!.registered?Math.round(stats!.checked/stats!.registered*100):0}%</h2><p>{stats!.checked} de {stats!.registered} participantes ingresaron</p></div><div className="progress"><span style={{width:`${stats!.registered?stats!.checked/stats!.registered*100:0}%`}}/></div></section></>}
 <section className="quicklinks"><Link href="/people"><strong>Personas →</strong><span>Buscar y gestionar registros</span></Link><Link href="/people/new"><strong>Registrar →</strong><span>Crear una credencial QR</span></Link><Link href="/scanner"><strong>Scanner →</strong><span>Validar entradas con cámara</span></Link></section></main></>;
}
