"use client";
import { useEffect, useMemo, useState } from "react";
import QRCode from "qrcode";
type Person={id:string;first_name:string;last_name:string;email:string;identification:string;phone:string;status:string;token:string;created_at:string;checked_in_at:string|null};
const labels:Record<string,string>={pending:"Pendiente",checked_in:"Ingresado",cancelled:"Anulado"};
export function PeopleTable({initialShow}:{initialShow?:string}) {
 const [items,setItems]=useState<Person[]>([]),[q,setQ]=useState(""),[status,setStatus]=useState("all"),[error,setError]=useState(""),[active,setActive]=useState<Person|null>(null),[qr,setQr]=useState(""),[busy,setBusy]=useState("");
 async function load(){const r=await fetch(`/api/people?q=${encodeURIComponent(q)}&status=${status}`);const d=await r.json();if(!r.ok)throw Error(d.error);setItems(d.participants);}
 useEffect(()=>{load().catch(e=>setError(e.message));},[q,status]);
 useEffect(()=>{if(active){QRCode.toDataURL(active.token,{width:320,margin:2}).then(setQr);}},[active]);
 useEffect(()=>{if(initialShow&&items.length){const found=items.find(x=>x.id===initialShow);if(found)setActive(found)}},[initialShow,items]);
 async function resend(p:Person){setBusy(p.id);setError("");try{const r=await fetch(`/api/people/${p.id}/email`,{method:"POST"});const d=await r.json();if(!r.ok)throw Error(d.error);alert("QR reenviado correctamente.");}catch(e){setError(e instanceof Error?e.message:"No fue posible enviar el correo.");}finally{setBusy("")}}
 async function cancel(p:Person){if(!confirm(`¿Anular el QR de ${p.first_name} ${p.last_name}?`))return;const r=await fetch(`/api/people/${p.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:"cancelled"})});const d=await r.json();if(!r.ok)setError(d.error);else load();}
 return <><div className="toolbar"><input aria-label="Buscar" placeholder="Buscar nombre, email o identificación…" value={q} onChange={e=>setQ(e.target.value)}/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Todos</option><option value="pending">Pendientes</option><option value="checked_in">Ingresados</option><option value="cancelled">Anulados</option></select></div>{error&&<p className="notice error">{error}</p>}
 <div className="tablewrap"><table><thead><tr><th>Persona</th><th>Identificación</th><th>Estado</th><th>Registro</th><th>Ingreso</th><th>Acciones</th></tr></thead><tbody>{items.map(p=><tr key={p.id}><td><strong>{p.first_name} {p.last_name}</strong><small>{p.email} · {p.phone}</small></td><td>{p.identification}</td><td><span className={`badge ${p.status}`}>{labels[p.status]}</span></td><td>{new Date(p.created_at).toLocaleString("es-EC")}</td><td>{p.checked_in_at?new Date(p.checked_in_at).toLocaleString("es-EC"):"—"}</td><td><div className="rowactions"><button onClick={()=>setActive(p)}>Ver QR</button><button onClick={()=>resend(p)} disabled={busy===p.id}>Reenviar</button>{p.status==="pending"&&<button className="dangerlink" onClick={()=>cancel(p)}>Anular</button>}</div></td></tr>)}{!items.length&&<tr><td colSpan={6} className="empty">No hay personas para mostrar.</td></tr>}</tbody></table></div>
 {active&&<div className="modalback" onClick={()=>setActive(null)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setActive(null)}>×</button><h2>{active.first_name} {active.last_name}</h2><p>{active.email}</p>{qr&&<img className="qrimage" src={qr} alt="Código QR personal"/>}<a className="button primary" href={qr} download={`qr-${active.identification}.png`}>Descargar QR</a><p className="muted">Código personal de un solo uso.</p></div></div>}</>;
}
